export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const SEND_FRIEND_REQUEST = "SEND_FRIEND_REQUEST";
export const ACCEPT_FRIEND_REQUEST = "ACCEPT_FRIEND_REQUEST";
export const DECLINE_FRIEND_REQUEST = "DECLINE_FRIEND_REQUEST";
export const GET_FRIEND_REQUEST = "GET_FRIEND_REQUEST";
export const GET_FRIEND_REQUEST_FAIL = "FRIEND_REQUEST_FAIL";
export const HANDLE_FRIEND_REQUEST = "HANDLE_FRIEND_REQUEST";
export const GET_ALL_FRIENDS = "GET_ALL_FRIENDS";
export const GET_FRIEND_FAIL = "GET_FRIEND_FAIL";
export const DELETE_FRIEND = "DELETE_FRIEND";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";